### ISSUE TITLE
Important Questions

### ISSUE THREAD

**Issue by EngyNasr** [AgreementMakerLight/AML-Project#15]
Kindly I have some questions regarding AML. 

1) If there is a possibility to understand more about the matchers used in AML and how they really work in order to match, with there different preferences and settings, I would be so grateful if you provided me with these information or where to find them.

2) How are the percentages of that matched entities are calculated ?

3) Is there a way in AML to check super or sub class or is it just equivalence relations between matched entities? 

4) How can I use the background Knowledge in AML  

Thanks you so much in advance.

**Comment by DanFaria** [comment]
Hi


1. Please check AML's original paper: http://disi.unitn.it/~p2p/RelatedWork/Matching/Feriae_AgreementMakerLight13.pdf
You can check also AML's annual OAEI results papers (found in the Ontology Matching Workshop website) throughout the years which detail changes to the matching algorithms since the original version.


2. AML uses a scoring system for name-based matching which is detailed in this article: https://link.springer.com/content/pdf/10.1007/978-3-642-41335-3_33.pdf
These scores are used as weighting factors in the similarity scores computed by the various matching algorithms (e.g., the StringMatcher would produce a string similarity score which would be multiplied by these weights).


3. AML's algorithms are prepared only to find equivalence relations.


4. AML's background knowledge strategy is detailed in this article: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0111226
You can add any ontology you want to use as background knowledge into AML's 'store/knowledge' directory, and it should automatically consider it as an valid background knowledge source.


Best regards

**Comment by EngyNasr** [comment]
Thank you so much :)

**Comment by liweizhuo001** [comment]
Hello, how to utlize AML for interactive matching track in OAEI. I do not find the executable file that can run in offline. Thank you.

**Comment by DanFaria** [comment]
Hi,

If you want to test AML in OAEI's interactive mode, you should:

1) Download the AML OAEI version for the SEALS client (https://github.com/AgreementMakerLight/AML-Project/releases/download/SEALS_OAEI2017/AML-SEALS_OAIE2017.zip)

2) Download the OAEI SEALS client (https://github.com/DanFaria/OAEI_SealsClient/releases/download/v7.0.4/seals-omt-client.jar)

3) Use the SEALS client to execute AML in interactive mode as per the OAEI instructions (https://github.com/DanFaria/OAEI_SealsClient/blob/master/SealsClientTutorial.pdf)

Best regards

**Comment by EngyNasr** [comment]
Hello :) 

Thanks again for your great answers they really helped a lot, 

I kindly have further related questions: 

1) based on question 1 related to the matchers explanations, I have read this paper before, and I wonder if you have another one that includes more deep explanations for the matchers.

2) Related to the forth question regarding the Background Knowledge, where can i find AML's 'store/knowledge' directory, to add my background Knowledge ontology.

3) My last question is regarding the custom match, specially when choosing property matcher, it throws an exception can you please guide me to solve this too. 

Thanks again for your great & kind help,
Best Regards

**Comment by EngyNasr** [comment]
Hello :) 

For the background knowledge, I figured out where to put my ontology, in "AML-Project / AgreementMakerLight / store / knowledge / ", but after that I have checked the setting of the custom match to check the background Knowledge list, but it empty.

Can you please help me on that too :)

**Comment by DanFaria** [comment]
Hi @EngyNasr,

1) I'm afraid we don't have any published paper with a more in-depth explanation for the matchers. You can give a look at the source code for the matchers if you want a more in-depth understanding of how they work (the code is usually well-documented and follows an identical structure for all matchers, so it should be straightforward to interpret). I can also answer any specific doubts you have about how the matchers work.

2) Please detail exactly how you are running AML and at which point in the process did you check the background knowledge list --- it should never be empty unless you removed the default background knowledge sources included with AML.

3) Please detail the exception you are having as well as the ontologies you are trying to match.

Best

**Comment by EngyNasr** [comment]
Thanks again :) 

1. Ok, great I will take a look on the code and thank you so much for the documentations.

2. Am using the jar file created to run AML, as explained in description. The list that I am talking about is not the one in the folder (the folder contains all the files as downloaded), I am speaking of the one the we get when we open AML jar file, choose the ontologies, choose custom match, then setting, then the list appears, this one is the empty one, I tried attaching the list i mean.

3. The exception is as follows:
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: edu/smu/tspell/wordnet/WordNetDatabase
	at aml.knowledge.WordNet.<init>(WordNet.java:47)
	at aml.util.NameSimilarity.<init>(NameSimilarity.java:35)
	at aml.match.HybridStringMatcher.<init>(HybridStringMatcher.java:68)
	at aml.match.AutomaticMatcher.matchClasses(AutomaticMatcher.java:273)
	at aml.match.AutomaticMatcher.match(AutomaticMatcher.java:94)
	at aml.AML.matchAuto(AML.java:712)
	at aml.ui.AMLMenuBar.run(AMLMenuBar.java:265)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassNotFoundException: edu.smu.tspell.wordnet.WordNetDatabase
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more

Best Regards

**Comment by EngyNasr** [comment]
![BK](https://user-images.githubusercontent.com/7595309/67678825-d884e500-f987-11e9-9e88-4ee08c0325d7.png)

**Comment by EngyNasr** [comment]
Also concerning the Background Knowledge ontology, I should add only the .owl file in the directory "\store\knowledge", or should I add something else

Thank again :)

**Comment by DanFaria** [comment]
Hi @EngyNasr,

Both your problems 2 and 3 are caused by the same problem: AML cannot find the store/knowledge folder.

Are you running the AML jar from the 3.1 release or did you clone the project then create the jar using Maven?

In either case, the AML jar file **must** remain within the folder structure it came in, as the program expects to find the 'log4j.properties' file and the directories 'store/' (with configurations) and 'store/knowledge' (with background knowledge, including the WordNet) in the same directory as the jar file, otherwise it won't be able to find them.

Please either place the AML jar file within its original directory or copy the log4j file and directories listed above to the same location as the jar file and try running AML again.

You only need to add the .owl file in the knowledge directory for AML to detect the ontology and try to use it as a background knowledge source. Note, however, that it will first test whether the ontology adds new information to the matching problem, and only use it if it does, as described in the background knowledge paper I listed previously.

Best

**Comment by EngyNasr** [comment]
Hello @DanFaria,

Can't thank you enough for your continuous help. 

I use mvn install to run AML, which creates a target folder where the jar file is places. I have moved the  'log4j.properties' file  and 'store' folder to the target folder where the jar file is.

Now I have: 

Achieved Point: The background ontologies appears in the list.

Not yet achieved:  When running automatic match, or keep the property matcher in the custom match I still get the exception:
Exception in thread "Thread-11" java.lang.NoClassDefFoundError: edu/smu/tspell/wordnet/WordNetDatabase
	at aml.knowledge.WordNet.<init>(WordNet.java:47)
	at aml.util.NameSimilarity.<init>(NameSimilarity.java:35)
	at aml.match.HybridStringMatcher.<init>(HybridStringMatcher.java:68)
	at aml.match.AutomaticMatcher.matchClasses(AutomaticMatcher.java:273)
	at aml.match.AutomaticMatcher.match(AutomaticMatcher.java:94)
	at aml.AML.matchAuto(AML.java:712)
	at aml.ui.AMLMenuBar.run(AMLMenuBar.java:265)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassNotFoundException: edu.smu.tspell.wordnet.WordNetDatabase
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more

 Kind Regards

**Comment by EngyNasr** [comment]
What I basically want to do with the background Knowledge ontology is that I am having 2 ontologies source and target, one includes 'Al' and the other includes 'Aluminium', and that applies to the whole periodic table. 

So I created an intermediate background Knowledge which states the equivalence between all periodic table symbols and their names. I now can see it in the background knowledge list but the results did not improve, I will re read the paper to see why that is happening. But If you can also direct me on that I would be so much grateful

**Comment by DanFaria** [comment]
Hi @EngyNasr,

The exception means that somehow the WordNet jaws.jar library is not being included in the Jar created by Maven. I will have some testing to do to figure out why and how to solve it.

In the meanwhile, since you apparently only want to run (not code in) AML, I recommend that you try downloading and running AML's stable 3.1 release: https://github.com/AgreementMakerLight/AML-Project/releases/download/v3.1/AML_v3.1.zip. This should give you no problems.

As for the background knowledge issue, please beware that AML's matching is lexical-based. This means that, in order for it to learn that Al and Aluminium are synonyms, you have to declare both as annotations (e.g. rdf:label) of the same OWL class. Declaring Al and Aluminium as two equivalent OWL classes will not work, and will actually preclude AML from matching the classes, since the equivalence is already expressed in the ontology, and AML only attempts to find equivalences that aren't.

**Comment by EngyNasr** [comment]
Thank you so much, it worked perfectly when using the labels instead :) 

Thanks again for your great support

**Comment by Alyadumi** [comment]
Hi

Thank you so much for your great work. I really appreciate the effort you have contributed to the ontology matching. 

I am trying to match ontologies provided by HOBBIT LINK DISCOVERY TASK AT OAEI 2017. Task 1 (Linking)  and Task 2 (Spatial).
I have run AML on different versions (AML_SEALS_OAEI2017, AML v3.1). Also updating the config.ini  file using (config.ini_instance-spimbench) but AML doesn't get out the right alignments.

Please kindly advise on how to proceed with the matching. What are the parameters that I need to change?

Thank you very much for your kind assistance in advance.

<img width="932" alt="Screen Shot 2021-02-06 at 18 53 34" src="https://user-images.githubusercontent.com/32763199/107124453-f8bb8780-68de-11eb-8f9d-e946359551bd.png">

<img width="1235" alt="Screen Shot 2021-02-06 at 22 26 57" src="https://user-images.githubusercontent.com/32763199/107124460-ff49ff00-68de-11eb-97a5-64e2e76adeed.png">

<img width="1230" alt="Screen Shot 2021-02-06 at 22 33 40" src="https://user-images.githubusercontent.com/32763199/107124463-01ac5900-68df-11eb-9948-19976f4e7459.png">

<img width="639" alt="Screen Shot 2021-02-07 at 00 46 14" src="https://user-images.githubusercontent.com/32763199/107124464-040eb300-68df-11eb-8b02-0b1a455c529e.png">

**Comment by DanFaria** [comment]
Hi,

The versions of AML for matching the Linking and Spatial tasks are
available only through the HOBBIT server, as AML-Linking and AML-Spatial
respectively.
These tasks require dedicated adaptations to the code in particular because
in the HOBBIT evaluation, only the instance data is provided to the system,
meaning we have had to hard-code the class data in order to participate in
these tracks (something which I've complained about, but to no avail).
I've been meaning to incorporate the code for these tasks into the main AML
code-base, but haven't gotten around to it yet.
The good news is that I'm going to be working full time on AML again
starting this month, and that is one of the things I'll definitely tackle.
For the time being, though, you'll have to run AML through HOBBIT to match
these tasks.

Best,

Daniel
