### ISSUE TITLE
Releasing AML 2019 version 

### ISSUE THREAD

**Issue by Remorax** [AgreementMakerLight/AML-Project#17]
Hi,

I notice in the "releases" tab that the latest release is the AML 2017 submission to OAEI. Can the 2019 submission be released as well?

We at IBM Research are also working on Ontology Alignment, and it would be great help to us if you were able to release the latest version of your code, especially AMLC.

Thanks for your time!

**Comment by DanFaria** [comment]
Hi @Remorax,

As far as releases go, we only publish stable versions of AML that can be run by end-users (or using the SEALS client, in the case of OAEI releases). We haven't uploaded releases for OAEI 2018 and 2019 because they are virtually identical to the OAEI 2017 version, but in any case, the latest end-user release is AML 3.1.

As for AMLC, which we used to compete in the Complex track, it is still very much work in progress. Handling complex ontology matching required substantial changes to the AML codebase, and we decided to incorporate other core changes that were long overdue. Our plan is to make a new AML 4.0 release that incorporates the complex matching features and overhauled code, but alas we haven't been able to devote the time necessary to fix all the bits that were broken by the overhaul (namely the GUI).

If you're interested in the source code, we always publish it here, even if it isn't ready for release yet. You can find the source code for complex matching under branch "dev", but keep in mind that several AML functionalities are still broken in this branch (it is capable of complex ontology matching but little else).

If you just want to test the AMLC version we submitted to the OAEI (which only runs using the SEALS client), I can share it directly with you via email.

In any case, we are glad to know that our efforts to tackle complex matching have been noticed by IBM research, and would welcome the prospect of a more direct collaboration if it were possible on your end. Please let us know.

Best,

Daniel

**Comment by Remorax** [comment]
Hey Daniel,

Thanks for the detailed response. 

For now, I am only interested in the source code so I'll surely check the dev branch. And yes, it would also be great if you could drop me an email of your submission to OAEI 2019 at [here](mailto:vivek.iyer@research.iiit.ac.in)!

Regarding a direct collaboration, unfortunately, I'm afraid it would neither be possible nor feasible at the current moment.

Best,
Vivek
